# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:Smelt (beta): A CLI tool for Minecraft mapmakers
description: > # this means to ignore newlines until "baseurl:"
    A CLI tool for Minecraft map makers; used to compile 
    MCC files into combined-command installers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smelt.gnasp.com" # the base hostname & protocol for your site
twitter_username: GnaspGames
github_username:  GnaspGames

# Build settings
markdown: kramdown
